name: enum_extension_annotation
description: enum extension annotation.
version: 1.0.0

environment:
  sdk: '>=2.14.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
